services:
  install-dependencies:
    container_name: install-dependencies
    build:
      context: .
      dockerfile: .dev/Dockerfile.install
    volumes:
      - ./:/usr/src/app
    command: npm install

  test:
    image: node:22-alpine
    container_name: test
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - backend
    environment:
      - DB_PATH=/data/db-users.sqlite
      - AUTH_API_BASE_URL=http://auth:3000
      - PORT=3000
      - OPEN_API_FILE=./dist/openapiDTO.json
      - API_AUTH_SECRET=${API_AUTH_SECRET:-test}
    depends_on:
      install-dependencies:
        condition: service_completed_successfully
      nginx:
        condition: service_healthy
    command: sh -c "npm run test"
