services:
  nginx:
    restart: on-failure
    build: services/nginx/
    container_name: nginx
    ports:
      - '8080:8080'
    networks:
      - backend
    volumes:
      - avatars:/usr/share/nginx/html/avatars:ro

  frontend:
    restart: on-failure
    build: services/frontend/
    container_name: frontend
    depends_on:
      - nginx
    networks:
      - backend

  pong-server:
    restart: on-failure
    container_name: pong-server
    build:
      context: .
      dockerfile: ./services/pong-server/Dockerfile
    depends_on:
      - nginx
      - frontend

  users:
    restart: on-failure
    container_name: users
    build:
      context: .
      dockerfile: services/users/Dockerfile
    depends_on:
      - nginx
      - frontend
      - auth
    networks:
      - backend
    volumes:
      - avatars:/user/src/app/public/avatars
      - users_db:/user/src/app

  auth:
    restart: on-failure
    container_name: auth
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    depends_on:
      - nginx
      - frontend
    networks:
      - backend

networks:
  pong:
    driver: bridge
  backend:
    driver: bridge

volumes:
  avatars:
  users_db:
