services:
  nginx:
    restart: on-failure
    build: services/nginx/
    container_name: nginx
    ports:
      - '8080:8080'
    networks:
      - backend
    volumes:
      - avatars:/usr/share/nginx/html/avatars:ro

  frontend:
    restart: on-failure
    build: services/frontend/
    container_name: frontend
    depends_on:
      - nginx
    networks:
      - backend

  pong-server:
     restart: on-failure
     container_name: pong-server
     build:
       context: .
       dockerfile: ./services/pong-server/Dockerfile
     depends_on:
       - frontend

  users:
    restart: on-failure
    container_name: users
    build:
      context: .
      dockerfile: services/users/Dockerfile
    depends_on:
      - frontend
      - auth
    networks:
      - backend
    volumes:
      - avatars:/app/avatars
      - db_users_data:/data
    environment:
      - DB_PATH=/data/db-users.sqlite
      - AUTH_API_BASE_URL=http://auth:3000
      - PORT=3000
      - OPEN_API_FILE=./dist/openapiDTO.json
  auth:
    restart: on-failure
    container_name: auth
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    depends_on:
      - frontend
    networks:
      - backend
    volumes:
      - db_auth_data:/data
    environment:
      - DB_PATH=/data/db-auth.sqlite
      - USERS_SERVICE_URL=http://users:3000
      - PORT=3000
      - OPEN_API_FILE=./dist/openapiDTO.json

  prometheus:
    image: prom/prometheus:v3.7.2
    container_name: prometheus
    networks:
      - backend
    ports:
      - "9090:9090"
    volumes:
      - ./services/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - auth
      - users

  grafana:
    image: grafana/grafana-oss:12.2.0-17142428006
    container_name: grafana
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./services/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus

networks:
  pong:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_auth_data:
  db_users_data:
  avatars:
  grafana_data:
