services:
  nginx:
    restart: on-failure
    build: services/nginx/
    container_name: nginx
    ports:
      - '8080:8080'
    networks:
      - backend
    volumes:
      - avatars:/usr/share/nginx/html/avatars:ro

  frontend:
    restart: on-failure
    build: services/frontend/
    container_name: frontend
    depends_on:
      - nginx
    networks:
      - backend

  pong-server:
     restart: on-failure
     container_name: pong-server
     build:
       context: .
       dockerfile: ./services/pong-server/Dockerfile
     depends_on:
       - nginx
       - frontend

  users:
    restart: on-failure
    container_name: users
    build:
      context: .
      dockerfile: services/users/Dockerfile
    depends_on:
      - nginx
      - frontend
      - auth
    networks:
      - backend
    volumes:
      - avatars:/app/avatars
      - db_users_data:/data
    environment:
      - DB_PATH=/data/db-users.sqlite
      - AUTH_API_BASE_URL=http://auth:3000
      - PORT=3000
      - OPEN_API_FILE=./dist/openapiDTO.json
  auth:
    restart: on-failure
    container_name: auth
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    depends_on:
      - nginx
      - frontend
    networks:
      - backend
    volumes:
      - db_auth_data:/data
    environment:
      - DB_PATH=/data/db-auth.sqlite
      - USERS_SERVICE_URL=http://users:3000
      - PORT=3000
      - OPEN_API_FILE=./dist/openapiDTO.json

networks:
  pong:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_auth_data:
  db_users_data:
  avatars:
