global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth:3000']

  - job_name: 'users'
    metrics_path: /metrics
    static_configs:
      - targets: ['users:3000']

  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mtail'
    metrics_path: /metrics
    static_configs:
      - targets: ['mtail:3903']

  - job_name: '2fa'
    metrics_path: /metrics
    static_configs:
      - targets: ['2fa:3000']

  - job_name: 'game'
    metrics_path: /metrics
    static_configs:
      - targets: ['game:3000']

  - job_name: 'social'
    metrics_path: /metrics
    static_configs:
      - targets: ['social:3000']

rule_files:
  - '/etc/prometheus/rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'
