global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth:3000']

  - job_name: 'users'
    metrics_path: /metrics
    static_configs:
      - targets: ['users:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    