checks:
  - check: message
    regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)|(Merge).*|(fixup!.*)'
    error: "The commit message should be structured as follows:\n\n
    <type>[optional scope]: <description>\n
    [optional body]\n
    [optional footer(s)]\n\n
    More details please refer to the wiki project page"
    suggest: please check your commit message whether matches above regex

  - check: branch
    regex: ^(bugfix|feature|hotfix|docs|refactor|chore)\/.+|(master)|(main)|(HEAD)|(PR-.+)
    error: "Branches must begin with these types: bugfix/ feature/ hotfix/ docs/ refactor/ chore/"
    suggest: run command `git checkout -b type/branch_name`


