name: Unit Tests

on:
  pull_request:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests via Makefile
        run: |
          # Install npm for test
          if make install; then
            echo "Npm installed succesfully."
          else
            echo "Npm installed failed."
            exit 1
          fi
          # build workspace packages
          if make build; then
              echo "Build completed successfully."
          else
              echo "Build failed. Please fix the build errors before merging."
              exit 1
          fi
          # Run unit tests via Makefile
          if make test; then
            echo "All unit tests passed successfully."
          else
            echo "Unit tests failed. Please fix the failing tests before merging."
            exit 1
          fi
